### ISSUE TITLE
Add a chapter about non-wireless, non-ethernet machine connections

### ISSUE THREAD

**Issue by PiotrZierhoffer** [renode/renode-docs#12]
This was asked about by @karlp and other users. 

While regular network is covered in relevant chapters, we'd benefit from having other connections documented as well:

- [x] UARTHub
- [ ] GPIOConnector
- [ ] USBConnector
- [ ] CANHub

**Comment by mateusz-holenko** [comment]
https://github.com/renode/renode-docs/commit/1f5b6d807a41419cba2086d38c9a4e864ebbc851 adds a section about the UART hub connections. @karlp, you might be interested

**Comment by mgielda** [comment]
The chapter is actually here! https://renode.readthedocs.io/en/latest/networking/machine-to-machine-connections.html 

Took a while, but happy to have it now.
