### ISSUE TITLE
docs.renode.io should take me to the docs

### ISSUE THREAD

**Issue by mithro** [renode/renode-docs#16]
It would be awesome if https://docs.renode.io/ took me to the renode docs. 

Depending on how you want to handle this there are two options;
 * set up readthedocs to use docs.renode.io as the preferred domain -- https://docs.readthedocs.io/en/stable/custom_domains.html
 * do a redirect on docs.renode.io to renode.rtfd.io

**Comment by mithro** [comment]
FYI - @mgielda

**Comment by PiotrZierhoffer** [comment]
Good idea! We added a redirection from docs.renode.io to readthedocs
