### ISSUE TITLE
UART integration issue. 

### ISSUE THREAD

**Issue by Nileshhampiholi** [renode/renode-docs#27]
I am trying to emulate a port and write some bytes to the port using python. 

I have followed the steps exactly for installation.

I am using Ubuntu 20.4

Following is the error message I get. I am also attaching an image for better understanding. 
(machine-0)  connector Connect sysbus.uart0 term
The following methods are available:
 - Void Connect (IEmulationElement connectee, IConnectable connector)
Usage:
 connector MethodName param1 param2 ...
There was an error executing command 'connector Connect sysbus.uart0 term'
Parameters did  not match the signature

![Screenshot from 2021-11-21 16-40-46](https://user-images.githubusercontent.com/19320161/142768851-8f0fac15-a0ee-4e47-848d-d01ed8165285.png)

**Comment by PiotrZierhoffer** [comment]
In this case you are missing the `sysbus.uart0`. First you need to load the actual machine: https://renode.readthedocs.io/en/latest/basic/machines.html#loading-platforms

I will add a clarification to the documentation.
