### ISSUE TITLE
maintain as part of renode

### ISSUE THREAD

**Issue by mkschreder** [renode/renode-docs#32]
Why is this repository maintained outside of renode? How do you plan to track versioning of docs vs versioning of main renode releases? 

It would be a good idea to maintain docs directly in renode repository so that documentation is always up to date.

**Comment by pgielda** [comment]
We prefer to keep docs separately for various reasons. Renode consists of many repositories, this is by far not the only one. Having said that we might pin specific commits to specific releases (if we're not doing that already).
